graph LR
    %% Główny punkt wejścia
    App[App]

    %% Warstwa Interfejsu Użytkownika
    subgraph UI_Layer [Warstwa interfejsu użytkownika]
        Panel_GUI[Panel_GUI]
        SideBar[SideBar]
        PPS[PointParticleSideBar]
        PopInfo[PopInfo]
    end

    %% Warstwa Symulacji Fizycznej
    subgraph Physics_Layer [Warstwa symulacji fizycznej]
        ImpulseCollector[ImpulseCollector]
        ObjectsManager[ObjectsManager]
        RealObject[RealObject]
        ForceManager[ForceManager]
        PhysicObject[PhysicObject]

        ImpulseCollector --- ObjectsManager
        ObjectsManager --- RealObject
        RealObject --o ForceManager
        RealObject --> PhysicObject
    end

    %% Warstwa Graficzna
    subgraph Graphics_Layer [Warstwa graficzna]

        Camera[Camera]
        Grid[Grid]
        Axes[Axes]
        DrawAssistance[DrawAssistance]

        DrawnObject[DrawnObject]
        Shapes[DrawnShapes: Circle, Rectangle...]
        VectorManager[VectorManager]
        Trajectory[Trajectory]

        DrawnObject --> Shapes
    end

    %% Relacje zewnętrzne i między warstwami
    App --- UI_Layer
    App --- Graphics_Layer
    App --- Physics_Layer

    Panel_GUI -.-> SaveManager
    RealObject --> DrawnObject
    RealObject --o Trajectory
    RealObject --o VectorManager

    Grid -.-> Camera
    Axes -.-> Camera
    DrawAssistance -.-> Camera
    Axes -.-> Grid
